### ISSUE TITLE
Bill 10 Twitter IDs behind login

### ISSUE THREAD

**Issue by edsu** [DocNow/catalog#8]
@pbinkley thanks for adding your dataset! I'd be curious to hear how well you thought the process worked. 

Also, I noticed that the url for the dataset http://dx.doi.org/10.7939/DVN/10971 sends me to a login page. Is that the intended behavior?

**Comment by pbinkley** [comment]
I had to get some help at the Dataverse end (I wasn't clear on the difference between public and released), but you should be taken straight through to the item now.

Adding to the catalog was easy. I've put in an issue https://github.com/DocNow/twarc/issues/127 to lobby for a ```twarc dehydrate``` command, to lower the barrier to creating sets of ids like this. I may get around to putting in a PR on this but probably not soon.

**Comment by edsu** [comment]
Thanks @pbinkley!
